- name: install required packages
  apt:
    name:
      - tzdata
      - locales
      - locales-all
    state: present

- name: define present locales
  locale_gen:
    name: "{{ locale_present }}"
    state: present
  with_items: "{{ locales_present }}"
  loop_control:
    loop_var: locale_present
  notify: reconfigure locales

- name: define absent locales
  locale_gen:
    name: "{{ locales_absent }}"
    state: absent
  with_items: "{{ locales_absent }}"
  loop_control:
    loop_var: locale_absent
  notify: reconfigure locales
