---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: role-locales
  vars:
    locales_present:
      - en_US.UTF-8
      - de_DE.UTF-8
    locales_language_packs_present:
      - language-pack-en
      - language-pack-en-base
    locales_absent: []
    locales_language_packs_absent: []
    locales_default:
      lang: en_US.UTF-8
