- name: Converge
  hosts: all
  become: True
  roles:
    - role: role-locales
  vars:

    locales_present:
      - en_US.UTF-8
      - de_DE.UTF-8

    locales_absent: []

    locales_default:
      LANG: en_US.UTF-8
